<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
  <head>
    
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title')</title>
    {{-- include all css files and meta tags --}}
    @yield('header')
    <!-- Scripts -->

    <style type="text/css" media="screen">
      @media (max-width: 991px){
header nav.navbar .navbar-brand img {
     max-height: 100% !important; 
}

}

.how-to-bid-wrap:before{
    display:none;
}
    </style>
 
  </head> 
  
  <body id="company-1" class="my-login-page"><div class="notify-container"></div>
  <div id="front" data-front-locale="en" data-site-currency="EUR">
    <header class="fixed-top" role="heading">
      <div class="topbar" style="background: #036eb5 !important;">
        <div class="container">
          <div class="topmenu">
            <div id="locale-settings">
              <div data-v-690f30e8="" class="lang-currency-country">
                <div data-v-690f30e8="" class="selected-options">
                <select name=""  class=" btn-sm shadow-sm border-0 btn-block text-white" style="background: #036eb5 !important;">
                  <option value="">Lang</option>
                   <option value="en">Eng</option>
                </select>
                </div>
                
              </div>
            </div>
            <ul class="d-flex justify-content-end">
               <li>
                <a href="{{ route('myaccount') }}" class="modal-tab-toggle" data-target="login-register" data-tab-content="1"> <span class="fa fa-user"></span>My Account </a>
              </li>
            @if (Auth::check())
            <li>
              <a href="javascript:void" onclick="$('#logout-formlogout').submit();"> <span class="fa fa-unlock"></span>Logout </a>
            </li>
            @else
            <li>
              <a href="{{ url('/register') }}" class="modal-tab-toggle" data-target="login-register" data-tab-content="1"> <span class="fa fa-user-plus"></span>Register </a>
            </li>
            <li>
              <a href="{{ route('login') }}" class="modal-tab-toggle" data-target="login-register" data-tab-content="0"> <span class="fa fa-lock"></span>Login </a>
              </li>
            
              @endif
              
              
            </li>
          </ul>
        </div>
      </div>
    </div>
    <form id="logout-formlogout" action="{{ route('logout') }}" method="POST" style="display: none;">
      @csrf
    </form>
    <nav class="navbar navbar-expand-lg" role="navigation">
      <div class="container">
      
        <a class="navbar-brand" href="{{ route('front-home') }}">
          <img src="{{ asset('img') }}/{{ config('custom_env_Variables.SITE_LOGO') }}" style="max-height: 104px;" />
        </a>
        <button class="ma5menu__toggle mobileMenueToggle" type="button">
        <span class="ma5menu__icon-toggle"></span> 
        <span class="ma5menu__sr-only">Menu</span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{{ route('front-home') }}">
                Online Auctions
              </a>
         
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ route('bid') }}">How to Bid</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ route('news') }}">News</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ route('contact') }}">Contact us</a>
            </li>
         
          </ul>
          <!-- ma5-mobile-menu generated by js start -->
       
          <!-- ma5-mobile-menu generated by js end -->
        </div>
      </div>
    </nav>
  </header>
  @include('includes-frontend.login-registerModal')
  @yield('content')



  
  
  <div class="ma5menu__container mobileopendertoggle " style="display: none;">
    <div class="ma5menu__head">
      <div class="ma5menu__header">
        <a class="ma5menu__home" href="/" tabindex="-1">
          <span class="ma5menu__logo"></span>
        </a>
        <a class="ma5menu__toggle" tabindex="-1">
          <span class="ma5menu__close"></span>
        </a>
      </div>
    </div>
    <div class="ma5menu__alert">
      <div class="ma5menu__alert-content"><span class="ma5menu__icon-up" aria-hidden="true"></span><span class="ma5menu__icon-up" aria-hidden="true"></span><span class="ma5menu__icon-up" aria-hidden="true"></span></div>
    </div>
    <div class="ma5menu__panel--active lvl-0 ma5menu__panel hasnt-scrollbar" data-ma5order="ma5-ul">
      <ul>
       
        <li data-ma5order="ma5-li-2">
          <a href="/">Online Auctions</a>
        </li>
          <li data-ma5order="ma5-li-2">
          <a href="{{ route('bid') }}">How to Bid</a>
        </li>
          <li data-ma5order="ma5-li-2">
          <a href="{{ route('news') }}">News</a>
        </li>
          <li data-ma5order="ma5-li-2">
          <a href="{{ route('contact') }}">Contact Us</a>
        </li>
       
       
      </ul>
    </div>

  </div>
  {{-- include all js files --}}
  @yield('footer')
  <!-- End of Page Wrapper -->

  <style type="text/css" media="screen">
    .togglemobileopenMenue{

          display: block !important;
    }
  </style>
</div>
</body>
</html>